[package]
name = "speedy"
version = "0.4.1"
authors = ["Jan Bujak <j@exia.io>"]
repository = "https://github.com/koute/speedy"
homepage = "https://github.com/koute/speedy"
documentation = "https://docs.rs/speedy/*/speedy/"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["serialization"]
categories = ["encoding"]
description = "A fast binary serialization framework"

[dependencies]
byteorder = "1"

[dev-dependencies]
speedy-derive = { version = "0.3", path = "speedy-derive" }

[profile.release]
panic = "abort"
